name: Build Next.js for Alwaysdata

on:
  workflow_dispatch:
  push:
    branches: [deploiement]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Next.js
        run: npm run build        
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}

      - name: Archive build artifacts
        run: |
          tar czf build-artifact.tar.gz .next node_modules package.json package-lock.json public app next.config.ts tsconfig.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build-artifact.tar.gz